# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleRows_dgc <- function(x, p, i, ncol, nrow, thresh) {
    .Call('_cygnus_scaleRows_dgc', PACKAGE = 'cygnus', x, p, i, ncol, nrow, thresh)
}

st_mats_perimeter <- function(Xvec) {
    .Call('_cygnus_st_mats_perimeter', PACKAGE = 'cygnus', Xvec)
}

get_e_minus_epaths_saddles <- function(epaths, saddles, N) {
    .Call('_cygnus_get_e_minus_epaths_saddles', PACKAGE = 'cygnus', epaths, saddles, N)
}

is_in_list <- function(target, mylist) {
    .Call('_cygnus_is_in_list', PACKAGE = 'cygnus', target, mylist)
}

mergeListsToArmaUVec <- function(list1, list2) {
    .Call('_cygnus_mergeListsToArmaUVec', PACKAGE = 'cygnus', list1, list2)
}

findDuplicates <- function(input) {
    .Call('_cygnus_findDuplicates', PACKAGE = 'cygnus', input)
}

update_V_cpp <- function(V_pcs, V_npts, V_perimeter, V_area, e_merge_from, e_merge_to, e_merge_edge_length, e_merge_area, e_merge_npts, e_merge_pcs, agg_mode) {
    invisible(.Call('_cygnus_update_V_cpp', PACKAGE = 'cygnus', V_pcs, V_npts, V_perimeter, V_area, e_merge_from, e_merge_to, e_merge_edge_length, e_merge_area, e_merge_npts, e_merge_pcs, agg_mode))
}

update_E_cpp <- function(V_pcs, V_perimeter, V_area, V_npts, E_from, E_to, E_npts, E_area, E_edge_length, E_pcs_merge, E_w, E_perimeter_merge, E_score_size, E_dscore, e_update, V_to_E_from, V_to_E_to, d_mu, d_sig, agg_mode, min_npts, max_npts) {
    invisible(.Call('_cygnus_update_E_cpp', PACKAGE = 'cygnus', V_pcs, V_perimeter, V_area, V_npts, E_from, E_to, E_npts, E_area, E_edge_length, E_pcs_merge, E_w, E_perimeter_merge, E_score_size, E_dscore, e_update, V_to_E_from, V_to_E_to, d_mu, d_sig, agg_mode, min_npts, max_npts))
}

merge_aggs_cpp <- function(V_pcs, V_area, V_perimeter, V_npts, E_from, E_to, E_npts, E_area, E_edge_length, E_pcs_merge, E_w, E_perimeter_merge, E_score_size, E_dscore, d_mu, d_sig, iter_max, agg_mode, dscore_thresh, min_npts, max_npts) {
    .Call('_cygnus_merge_aggs_cpp', PACKAGE = 'cygnus', V_pcs, V_area, V_perimeter, V_npts, E_from, E_to, E_npts, E_area, E_edge_length, E_pcs_merge, E_w, E_perimeter_merge, E_score_size, E_dscore, d_mu, d_sig, iter_max, agg_mode, dscore_thresh, min_npts, max_npts)
}

foo_triplets_edges <- function(triplets, edges) {
    .Call('_cygnus_foo_triplets_edges', PACKAGE = 'cygnus', triplets, edges)
}

do_dmt_forest_cpp <- function(f, edges_from, edges_to, edges_f) {
    .Call('_cygnus_do_dmt_forest_cpp', PACKAGE = 'cygnus', f, edges_from, edges_to, edges_f)
}

trace_back_cpp <- function(v0, vcrit, parent_edge, parent) {
    .Call('_cygnus_trace_back_cpp', PACKAGE = 'cygnus', v0, vcrit, parent_edge, parent)
}

trace_epaths_cpp <- function(saddles, vcrits, edges_from, edges_to, parent_edge, parent) {
    .Call('_cygnus_trace_epaths_cpp', PACKAGE = 'cygnus', saddles, vcrits, edges_from, edges_to, parent_edge, parent)
}

get_e_sep <- function(epaths, saddles, nedges) {
    .Call('_cygnus_get_e_sep', PACKAGE = 'cygnus', epaths, saddles, nedges)
}

prune_e_sep <- function(edges, ntris, is_tri_external, e_sep) {
    .Call('_cygnus_prune_e_sep', PACKAGE = 'cygnus', edges, ntris, is_tri_external, e_sep)
}

nn_touches_2_vertices <- function(nn_touches, triplets) {
    .Call('_cygnus_nn_touches_2_vertices', PACKAGE = 'cygnus', nn_touches, triplets)
}

smooth_field_cpp <- function(pvec, adj_i, adj_p, field, coords, distance, similarity) {
    .Call('_cygnus_smooth_field_cpp', PACKAGE = 'cygnus', pvec, adj_i, adj_p, field, coords, distance, similarity)
}

compress_field_cpp <- function(field) {
    .Call('_cygnus_compress_field_cpp', PACKAGE = 'cygnus', field)
}

estimate_field_cpp <- function(coords, embeddings, adj_i, adj_p) {
    .Call('_cygnus_estimate_field_cpp', PACKAGE = 'cygnus', coords, embeddings, adj_i, adj_p)
}

assign_unique_rowid_cpp <- function(X, Y) {
    .Call('_cygnus_assign_unique_rowid_cpp', PACKAGE = 'cygnus', X, Y)
}

init_edges_cpp <- function(triplets, pts, tris) {
    .Call('_cygnus_init_edges_cpp', PACKAGE = 'cygnus', triplets, pts, tris)
}

init_tris_cpp <- function(triplets, pts) {
    .Call('_cygnus_init_tris_cpp', PACKAGE = 'cygnus', triplets, pts)
}

mapToConsecutivePositions <- function(numbers) {
    .Call('_cygnus_mapToConsecutivePositions', PACKAGE = 'cygnus', numbers)
}

splitSequence <- function(y) {
    .Call('_cygnus_splitSequence', PACKAGE = 'cygnus', y)
}

findLargestComponentEulerCycle <- function(edges) {
    .Call('_cygnus_findLargestComponentEulerCycle', PACKAGE = 'cygnus', edges)
}

get_agg_to_boundary_edge <- function(E, n_agg) {
    .Call('_cygnus_get_agg_to_boundary_edge', PACKAGE = 'cygnus', E, n_agg)
}

get_agg_to_edge <- function(edges, naggs, always_include_boundary) {
    .Call('_cygnus_get_agg_to_edge', PACKAGE = 'cygnus', edges, naggs, always_include_boundary)
}

get_boundary_graph_cpp <- function(e_dual, i_pts, e_prim, E, ntris) {
    .Call('_cygnus_get_boundary_graph_cpp', PACKAGE = 'cygnus', e_dual, i_pts, e_prim, E, ntris)
}

trace_polygons_cpp <- function(edges, naggs, ntris, pts_dmt_component) {
    .Call('_cygnus_trace_polygons_cpp', PACKAGE = 'cygnus', edges, naggs, ntris, pts_dmt_component)
}

trace_polygons_pts_cpp <- function(edges, naggs) {
    .Call('_cygnus_trace_polygons_pts_cpp', PACKAGE = 'cygnus', edges, naggs)
}

